### PR TITLE
updated bottom nav screen titles

### PR DESCRIPTION
**Pull request by RyanTG**

### CODE REVIEW

**Comment by RyanTG** [comment]
location list styles are still ongoing.

In order for the right arrow to be positioned in the same spot, I gave the location info container width of 95%. This might look imperfect on some phones. I'd rather do width: `100% - width of arrow icon`.

I also don't like how the year/man of the machines is bold. But I couldn't figure out how to separate that style from the machine name.

**Comment by bpoore** [comment]
@RyanTG, based on the API response, making just the title bold is more complicated because we are getting back fields of 'machine names' with the manufacturer and year appended to the name. On the location list screen, the name, manufacturer and year are all separated fields being concatenated into a string. I'm not sure what the data in the database looks like, but I can add regex to bold up until the last instance of a '(' character which in most if not all cases will fix this? What do you think?

**Comment by RyanTG** [comment]
Thanks. Uh, let’s not worry about it now. Not worth the effort.

**Comment by bpoore** [comment]
This should do it dbb25be85267df39340b1556313d2715f50bacd8. We'll want to keep an eye out for funkiness as we're just chopping up the string that comes back.

**Pull request merged**
