### PR TITLE
added ios icon

### PR DESCRIPTION
**Pull request by RyanTG**
Does this seem legit?

I'm following https://docs.expo.io/versions/latest/guides/app-icons/ & https://docs.expo.io/versions/latest/workflow/configuration/#icon

Just want to make sure the path is correct in app.json, as well as the key format.

I'll do android next.

### CODE REVIEW

**Comment by RyanTG** [comment]
Or should it be like:

"icon": {
  "ios.icon": "app/assets/images/ios-icon.png"
}

**Comment by RyanTG** [comment]
I probably need to make a smaller splash icon.

**Comment by bpoore** [comment]
It looks like the `android.icon` and `ios.icon` syntax is for a newer version of Expo than we are currently using. In order to build the apk / ipa files we need a couple more fields in the app.json as well. I'm thinking for now, we have it set up and switch out OS specific icons when we do the separate builds.

**Comment by RyanTG** [comment]
Ah, ok.

Making icons is a bit of a pain, since both platforms require so many different versions of the icons. I was hoping Expo would generate those automatically! I'll look for some other generators. I'm sure there are some that will automatically create the whole set, and then we can manually plop them into the builds.

**Comment by RyanTG** [comment]
So you mean, we put the android icon in app.json when we build to android, and then swap out the icon before building to ios? Just making sure.

**Pull request merged**
