### PR TITLE
search bar style on map screen

### PR DESCRIPTION
**Pull request by RyanTG**
haven't gotten to the actual modal part of the modal yet. But the search bar on the map screen was too wide on my lil phone.

### CODE REVIEW

**Comment by RyanTG** [comment]
It would be cool if the cursor was focused on the input when the modal first opens. I could probably figure that out. I just wanted to put that on the record.

**Comment by RyanTG** [comment]
I did the focus on input thing. Very easy.

It would be cool if that "clear the text" button didn't show up until a character had been typed. It's kind of confusing to see it when no characters are in the input.

**Comment by RyanTG** [comment]
I did the focus on input thing. Very easy.

It would be cool if that "clear the text" button didn't show up until a character had been typed. It's kind of confusing to see it when no characters are in the input.

**Comment by bpoore** [comment]
@RyanTG, good call, got the clear text button to only show up if there's text to clear. 

I merged this PR with the additional change. On my iPhone X simulator the search bar should be pulled down some. 
Screen Shot 2019-03-23 at 10 35 53 PM

**Pull request merged**
