### PR TITLE
Callout style themefollow

### PR DESCRIPTION
**Pull request by ErikGraciosa**
- added tooltip as recommended by react-native-maps docs
- moved some styles to inline styles

Not sure the organization of the getStyles function. Just put them near each other near the top.

### CODE REVIEW

**Comment by ErikGraciosa** [comment]
Didn't see all the changes to the package-lock.json, not sure why so many differences there.

**Comment by RyanTG** [comment]
Thanks, Erik! Overall looks great.

- On iOS, the arrow is not aligned well. If you don’t have access to an iOS device/emulator, then I can work on this. The arrow positioning is kind of hacked - perhaps there’s a way to do it better. With vertically alignment or flexbox or something.
- I would like to see a dropshadow (only in light mode). The same shadow style we use elsewhere.
- I don’t love how there isn’t a little arrow notch that points to the map marker. Is that an option with tooltips?

Not sure what’s up with package-lock.json, but it could be from you having a cleaner project.

4245159D-A2EB-4673-827A-4921BF2FCDA0

**Comment by bpoore** [comment]
Thanks @ErikGraciosa! This is awesome! @RyanTG is going to have the final say on any design choices... overall, I think this is a very nice improvement and some good clean-up of existing in-line styles.

Only thing on my end- if you weren't updating anything in the package.json, I don't know why there would be changes to the package-lock.json. I suspect it may be a node version difference? I think we should figure out what is going on with that before we merge. I can help look into what's going on there.

**Comment by RyanTG** [comment]
In case it helps, I'm using node 14.7.0

**Comment by bpoore** [comment]
I messed around with this a bit and I suspect it is a node version difference. With node 12 and 16, there was no difference to the lockfile. I had node 9 in my nvm list, tried that and it caused a diff in the package-lock.json. I think the npm version is fine because the lockfileVersion is set to 2 in the PR... that would be another source potentially causing differences, but doesn't appear to be the source in this case.

**Comment by RyanTG** [comment]
Erik - what’s your opinion on the “right arrow” icon on the callout? Do you think it’s necessary? We’re just trying to communicate that it’s clickable, and this is a standard way to show that. But maybe we don’t need it.

**Comment by ErikGraciosa** [comment]
I like the right arrow as a indicator for being clickable. I saw some of the styling was using absolute positioning so I didn't change anything there. I'll adjust to a relative positioning to improve and checkout out the emulators to view.
Drop shadow I'll copy over.
Arrow notch I also like, I'll add back(not sure if an option or will need to build).
My node version is 15.3.0. I'll try to upgrade to 16 and see what happens.

**Comment by RyanTG** [comment]
Not sure if this is a good idea, but it’s an idea: using an icon, like a caret-down one, and positioning it on the bottom edge so it looks like a little down arrow coming out of the bubble.

These are the icons we have easy access to: https://icons.expo.fyi/
And I think it’s preferable to make use of a library that we’ve already imported into this screen (rather than importing another library just for one icon).

**Comment by bpoore** [comment]
@ErikGraciosa, could you try:
* reverting the changes to the package-lock.json file here
* rm -rf node_modules
* npm cache clean --force
* npm i

**Comment by RyanTG** [comment]
Hi @ErikGraciosa. With the following (currently open) PR - https://github.com/bpoore/pbm-react/pull/389 - your branch will be a bit behind. Most notably, iOS devices will use Apple Maps and not Google Maps. Apple Maps uses their own marker callout design. And I'm not sure if it's possible to overwrite it with our own customization.

Also in that PR are some font updates that impact your work.

**Comment by bpoore** [comment]
@RyanTG, out of curiosity, what are we getting out of going to Apple Maps for iOS? Especially if by chance that means we can't customize the marker callout design?

**Comment by RyanTG** [comment]
1. We were originally using Apple Maps on iOS (prior to dark mode).
2. People complained when we switched to google maps.
3. From what I can, it’s a faster/smoother experience on iOS. Check out how the callouts pop-up. It’s nice, and google maps is clunky by comparison.

**Comment by bpoore** [comment]
Styling the callout looks like it will work with Apple Maps

IMG_6395

**Comment by RyanTG** [comment]
Awesome!

**Comment by ErikGraciosa** [comment]
@RyanTG Is the upgrade to "react-native-maps": "0.29.0" what enables the iOS vs google maps on apple/android? Should I pull down the branch with PR #389 and edit from there?

> Hi @ErikGraciosa. With the following (currently open) PR - #389 - your branch will be a bit behind. Most notably, iOS devices will use Apple Maps and not Google Maps. Apple Maps uses their own marker callout design. And I'm not sure if it's possible to overwrite it with our own customization.
> 
> Also in that PR are some font updates that impact your work.

**Comment by RyanTG** [comment]
Yes and yes.

it’s for this issue https://github.com/bpoore/pbm-react/issues/345

**Comment by ErikGraciosa** [comment]
> @ErikGraciosa, could you try:
> 
> * reverting the changes to the package-lock.json file here
> * rm -rf node_modules
> * npm cache clean --force
> * npm i

Updated to node 16.9.0 and ran those commands and that got it down to a 2 line diff and I removed those differences manually.

**Comment by ErikGraciosa** [comment]
> Not sure if this is a good idea, but it’s an idea: using an icon, like a caret-down one, and positioning it on the bottom edge so it looks like a little down arrow coming out of the bubble.
> 
> These are the icons we have easy access to: https://icons.expo.fyi/
> And I think it’s preferable to make use of a library that we’ve already imported into this screen (rather than importing another library just for one icon).

@RyanTG trying this carrot idea out but found that iOS will dynamically move the carrot based on where the marker is. Reading through the docs and trying to see if anyone else has already solved this problem. Android looks to always center the callout over the marker.

**Comment by RyanTG** [comment]
From Beth’s screenshot, it looks like we can simply use their container and only change the color (it’s already rounded and nice looking). Doesn’t seem like we need to replace it entirely.

**Comment by bpoore** [comment]
The screenshot I put up was applying the changes in this PR to the updated styles branch.

**Comment by RyanTG** [comment]
Ah gotcha.

From what I'm seeing, custom callouts in iOS should still include that down arrow by default (if customized according to the docs).
https://camo.githubusercontent.com/1ff889206ec013ed96c9b5045b07753598b9961ced4545c31f6e28f8ed875678/687474703a2f2f692e67697068792e636f6d2f78543737584e6550476e4d49494470626e712e676966

which I think is using this: https://github.com/react-native-maps/react-native-maps/blob/ad1f3a493e36e305661f383b4bb938a8a52c6269/example/examples/CustomCallout.js

**Comment by RyanTG** [comment]
Just a note that this branch is behind. We had to change back to google maps for iOS due to one feature missing on Apple Maps.

**Comment by ErikGraciosa** [comment]
I've been keeping up with the messages on the other PRs. I'm familiar with dotenv(I like it), curious how you set the env variables for the android and iOS apps. 

As for the arrows, i've been trying to get a solution that works for android and iOS, and then was poking around on the website version and saw sometimes the callout box will open below the pin. Is there a standard way to look at the web version in expo? I get this error when I try to start via 'w | open web' after 'expo start' command.


`Failed to compile.
./app/index.js
Module not found: Can't resolve 'react-native-web/dist/exports/Appearance' in 'C:\Users\erikg\pbm-react-forked\pbm-react\app'
Error from chokidar (C:\): Error: EBUSY: resource busy or locked, lstat 'C:\DumpStack.log.tmp'`

**Comment by RyanTG** [comment]
The website is a totally different project! https://github.com/scottwainstock/pbm

It’s a Ruby on Rails project, and predates the RN app by many years. The RN app uses the api from this website project.

**Comment by bpoore** [comment]
@ErikGraciosa, prior to moving to dotenv, Ryan was manually adding the required secrets to our app.json file (where the necessary env vars are set for iOS and Android), then removing them before committing changes. The issue being you can't interpolate variables into json files. Ryan discovered it is possible to use a different file type, app.config.js which does allow us to interpolate variables. While updating the filetype, it seemed as good a time as any to move to using .env to store our secrets as that's typical for JS projects, so now where Ryan was manually updating the config necessary for the given apps, we just reference [process.env](https://github.com/bpoore/pbm-react/blob/master/app.config.js#L44)

**Comment by RyanTG** [comment]
Hi @ErikGraciosa we have another release coming in the next week or two. Just checking if you expect to work on this anymore, or should we close it?

**Comment by RyanTG** [comment]
Yeah, seems like this should start fresh. There is a pending PR from me, though, to get everything up to speed. You could wait until Beth merges that. 

The only issue on iOS was that the little down arrow wasn't there, right? If that is the case, I think we should just apply the changes for both android/ios. That arrow thing seems minor.

**Comment by ErikGraciosa** [comment]
Closing, will create new branch off master since this one is very behind.

**Pull request closed without merging**
