### PR TITLE
Added a Resources page.

### PR DESCRIPTION
**Pull request by RyanTG**
Might not be final... but it's a start.

Believe it or not, I had to use this component in order to scale the logos correctly. https://github.com/ihor/react-native-scalable-image
Turns out that when you use resizeMode to fit the image width on the page, the image height isn't recalculated... So like, the image scales correctly, but there is top/bottom padding for the _full size_ of the image. Basically, this means that there was weird white space above/below the logos. I spent a while on this, because I was utterly confused. This component recalculates the height.

### CODE REVIEW

**Comment by bpoore** [comment]
This is great @RyanTG! I love the images on this new screen! I'm also really digging the new icons you've put in here and there! 

Content-wise- how do we feel about including a section linking to IFPA? Dennis and I read through the rest of the content together and thought it was excellent. The only feedback Dennis had was that we could potentially point out that the pintips is specifically tips for game strategy / how to approach games, perhaps just adding the `how to play` to the blurb? 

> is a great place to quickly pick up some quick tips about how to play specific machines. And it's very easy to contribute your own tips!

Only thing code-wise I would like to see before we merge this is for the lint to pass. I should set up lint to run on PR... will try to get to that soon. There are a lot of unused imports and variables in Resources.js. If this is otherwise ready to merge, I'm happy to take care of the fixes, otherwise, would you mind fixing when you next push up?

**Comment by RyanTG** [comment]
Oh ya, IFPA is a great idea, as well as the “how to play” text. Thanks!

I started with the About screen when I made this. I stepped a lot out, but obviously I missed stuff. I’ll fix the lint stuff. But, ummm, I can’t remember how to run a lint test.

**Comment by bpoore** [comment]
`npm run lint`

**Comment by RyanTG** [comment]
Ok, I think this is ready now.

**Pull request merged**
